# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def calendar
  pod 'JTAppleCalendar'
end


def test_pods

end

target 'TheCalendarApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  calendar
  pod 'Nuke'

  target 'TheCalendarAppTests' do
    inherit! :search_paths
    test_pods
  end

end
