# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TheCalendarApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TheCalendarApp

  target 'TheCalendarAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TheCalendarAppUITests' do
    # Pods for testing
  end

end
